# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ lib, stdenv, buildGoPackage }:

buildGoPackage rec {
  name = "terraform-docs-unstable-${version}";
  version = "2017-12-21";
  rev = "059271126935300cb9a7cf38445d1785596fedfc";

  goPackagePath = "github.com/segmentio/terraform-docs";

  src = builtins.fetchGit {
    inherit rev;
    url = "https://github.com/segmentio/terraform-docs";
  };

  goDeps = ./deps.nix;

  meta = with lib; {
    description = "Generate docs from terraform modules";
    homepage = https://github.com/segmentio/terraform-docs;
    platforms = platforms.linux ++ platforms.darwin;
    license = licenses.mit;
  };
}
