# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/hashicorp/hcl";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/hcl";
      rev = "ef8a98b0bbce4a65b5aa4c368430a80ddc533168";
      sha256 = "1qalfsc31fra7hcw2lc3s20aj7al62fq3j5fn5kga3mg99b82nyr";
    };
  }
  {
    goPackagePath = "github.com/tj/docopt";
    fetch = {
      type = "git";
      url = "https://github.com/tj/docopt";
      rev = "c8470e45692f168e8b380c5d625327e756d7d0a9";
      sha256 = "06h8hdg1mh3s78zqlr01g4si7k0f0g6pr7fj7lnvfg446hgc7080";
    };
  }
]
